name: AllergyLab CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v4
    - name: Build images
      run: |
        cd Part7a
        docker build -t ${{ secrets.DOCKER_USERNAME }}/al-app:latest ./app
        docker build -t ${{ secrets.DOCKER_USERNAME }}/al-email:latest ./email
        docker build -t ${{ secrets.DOCKER_USERNAME }}/al-db-loader:latest ./db-loader
    - name: Log in to Docker
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Push images to DockerHub
      run: |
        docker push ${​{ secrets.DOCKER_USERNAME }}/al-app:latest
        docker push ${​{ secrets.DOCKER_USERNAME }}/al-db-loader:latest
        docker push ${​{ secrets.DOCKER_USERNAME }}/al-email:latest        
deploy:
  needs: [build]
  runs-on: ubuntu-latest     
  steps:
  -name: '**PLACEHOLDER: DEPLOY TO KUBERNETES**'   
  run: echo "This is where you would add steps to deploy to Kubernetes or your hosting provider of choice. You can use the Docker images built in the previous step." 
  -name: Run containers
  run: |
    docker run -d --name app -p 3006:3006 --link dbhost --link redis-server ${​{ secrets.DOCKER_USERNAME }}/al-app:latest
    docker run -d --name dbhost -e MYSQL_ROOT_PASSWORD=yourpassword ${​{ secrets.DOCKER_USERNAME }}/al-dbhost:latest
    docker run -d --name email -p 25:25 --link redis-server ${​{ secrets.DOCKER_USERNAME }}/al-email:latest
    